OBJECTS = cbuffer.o ctcp.o async_loop.o async_tcp.o

CFLAGS = -fPIC -I/usr/local/include
LDFLAGS = -shared -L/lib -L/usr/local/lib -luv -lstdc++

.SUFFIXES: .cpp .o
.DEFAULT: libasync.so

.cpp.o:
	clang++ ${CFLAGS} -c $<

libasync.so: ${OBJECTS}
	clang++ ${LDFLAGS} ${OBJECTS} -o $@

clean:
	rm -f *.o ; rm -rf *.so
