(import (chezscheme) (chez-async internal io-runtime) (chez-async high-level io-proc))
(define fail 0)
(define (check n ok?) (printf "  ~a ~a~n" (if ok? "✓" "✗") n) (unless ok? (set! fail (+ fail 1))))
(printf "S3 io-proc gate…~n")
(io-runtime-start!)
(check "io-run /bin/true → 0" (= 0 (io-run "/bin/true")))
(check "io-run /bin/false → 非0" (not (= 0 (io-run "/bin/false"))))
(let ([r (io-run/output "/bin/echo" "hello" "世界")])
  (printf "    echo 输出: ~s (code ~a)~n" (utf8->string (cdr r)) (car r))
  (check "io-run/output echo 退出码 0" (= 0 (car r)))
  (check "io-run/output 捕获 stdout" (string=? (utf8->string (cdr r)) "hello 世界\n")))
(check "无 process 泄漏" (= 0 (io-live-processes)))
(check "无 task 泄漏" (= 0 (io-live-tasks)))
(io-runtime-stop!)
(if (= fail 0) (begin (printf "~n✅ io-proc gate 通过。~n") (exit 0)) (exit 1))
